# frozen_string_literal: true
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/neysofu/lecasedipaola" }

gem 'jekyll'
gem 'github-pages', group: :jekyll_plugins
gem 'jekyll-email-protect'
gem 'jekyll-sitemap'
